services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'busbooking'
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "80:80"
